version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "82:80"
    env_file:
      - .env
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/local/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mongodb
    networks:
      - laravel
  php:
    build: ./docker/php7-fpm
    volumes:
      - ./:/var/www/project
    networks:
      - laravel
    env_file:
      - .env
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: .env
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    ports:
      - 27017:27017
    networks:
      - laravel

volumes:
  mongodb_data:
    driver: local

networks:
  laravel:
    driver: bridge